### ISSUE TITLE
Ideas for new Commands / Constants

### ISSUE THREAD

**Issue by Mr-Xcoder** [Adriandmen/05AB1E#121]
I've been thinking about this for a while now and it is apparent to me that the following would be really useful:

 - 2 `ž`-constants: 
   - [x] `aeiouAEIOU`  (or `AEIOUaeiou`) – alias for `žMDu«`
   - [x] `aeiouyAEIOUY` (or `AEIOUYaeiouy`) – alias for `žODu«`
- 2 two-byte command:
   - [ ] Extended Transliteration / Replacement – I am not sure if one of the current commands already achieves this, to be honest – (maybe `.‡`): Given a string and a list containing the replacements achieve something like this: `"Elephant" [["AEIOU", "aeiou"], ["U", "u"]] .‡` (I prefer this one) or `"Elephant" [["AEIOU", "U"],  ["aeiou", "u"]] .‡` would yield `"Uluphunt"`. Overloads for standalone strings rather than arrays would also be cool: `"elephant" "aeiou" "u"` would yield `"uluphunt"` 
   - [x] Interchange capitalisation (maybe `.Ï`). Example: `"CoDeGoLf" "abcdefgh" .Ï` would yield `"AbCdEfGh"`. In case the two strings would not match in length, the remaining characters would just be left as-is.
 
[Example](https://codegolf.stackexchange.com/q/171588/59487) where those all could be useful – The current answer is (20 bytes):

    lžMÃÙεžMDu«s5×Du«‡}»

Using the first suggestion, this could be 17 bytes:

    lžMÃÙεž?s5×Du«‡}»

Using extended transliteration alongside interchanging capitalisation would be even stronger. An outline of the technique: Keep only the vowels, deduplicate, map over those, extended transliterate from `aeiou` to the current vowel (`y`), then interchange capitalisation with the input and join by newlines.

**Comment by Mr-Xcoder** [comment]
@Adriandmen Any thoughts on this?

**Comment by Adriandmen** [comment]
@Mr-Xcoder Thank you for the suggestion! I have implemented the constants and the capitalization exchange command: https://github.com/Adriandmen/05AB1E/pull/122.

I'm not sure about the extended transliteration/replacement command. The way the parameters should be given looks very clumsy. Perhaps rather than `[["AEIOU", "aeiou"], ["U", "u"]]`, would `["AEIOU", "aeiou"], ["U", "u"]` (as two separate elements) work?

**Comment by Mr-Xcoder** [comment]
@Adriandmen That would work too for the extended transliteration command. It's up to you if you implement it or not anyway :)

**Comment by Mr-Xcoder** [comment]
Implemented, except for extended transliteration, in https://github.com/Adriandmen/05AB1E/pull/122.
