### ISSUE TITLE
How to pass command line arguments in 05AB1E

### ISSUE THREAD

**Issue by MortezaRahmaniJRP** [Adriandmen/05AB1E#156]
Hi, everyone!
I am a Windows guy and use command [line] prompt, so how...?
`osabie arg1 arg2 ...argN`

**Comment by Adriandmen** [comment]
Hi @MortezaRahmaniJRP. Running an osabie file is done as follows:

<pre>
escript osabie <<i>05AB1E file path</i>>
</pre>

You can find more information about this on the [README section](https://github.com/Adriandmen/05AB1E#execution).

**Comment by MortezaRahmaniJRP** [comment]
oh excuse me:
`escript osabie <05AB1E file path> arg1 arg2 ... argN`
