### ISSUE TITLE
Add join and print command

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#34]

**Comment by GolfingSuccess** [comment]
Have the commands been added yet? I think it's simple: pop two stack items and join, or pop ToS and print it (no trailing newline)>

**Comment by Adriandmen** [comment]
On second thought, this command will not be added to 05AB1E. Since all 1-byte commands are already used.

**Comment by GolfingSuccess** [comment]
@Adriandmen Come on, you're so evil!
