### ISSUE TITLE
Add a surround command

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#37]
ayyeee lmaaoo

**Comment by ConorOBrien-Foxx** [comment]
what would this do?

**Comment by Adriandmen** [comment]
For example, surrounding the string `-----` with `+`, would become `+-----+`. 

Alternatively for arrays: `[1, 2, 3, 4, 5]` and `0` would become `[0, 1, 2, 3, 4, 5, 0]`.

**Comment by vendethiel** [comment]
what should the sigil be?

**Comment by Adriandmen** [comment]
Sigil?

**Comment by vendethiel** [comment]
command

**Comment by Adriandmen** [comment]
Probably a 2-char command, because I don't use it a lot. Something like `.ø`.

**Comment by vendethiel** [comment]
okay, so `current_command == ".\u00f8"`. I'll take a look at it :).

**Comment by Adriandmen** [comment]
It hasn't been implemented yet, but I'll let you know when it is :P.

**Comment by vendethiel** [comment]
no, I meant I'll take a stab at implementing it

**Comment by Adriandmen** [comment]
Oh, that is very kind of you, thanks :).

**Comment by vendethiel** [comment]
A few questions...

- Not sure what should the order of arguments be? array then value?
- What should it do (if anything) on ints?
- some parts of the code use `type(a) is list`, some `is_array(a)`, which is the preferred way?

**Comment by vendethiel** [comment]
What I currently have:

```
$ cat test                                                                                                                                                                                                                            :(
.ø
$ python3 05AB1E.py test
[1,2]
3
['3', 1, 2, '3']
```

**Comment by Adriandmen** [comment]
The first thing that is being popped from the stack is the value and after that the array/string/int is popped (for example `"abc""-".ø` should give `-abc-`). If the value is an integer, it needs to be converted to a string first.

`is_array(a)` is used when a string is an array, but in the form of a string, so the preferred way would be `type(a) is list`. The example you have given looks perfect!

**Comment by vendethiel** [comment]
Mmh, it seems the order is reversed between CLI and Stack?

```
$ cat test
"abc""-".ø
$ python3 05AB1E.py test
-abc-
```

Looks good? However...

```
$ cat test                                                                                                                                                                                                                           
.ø
$ python3 05AB1E.py test
abc
-
abc-abc
```

I don't know the language very much, so it could be blindingly obvious...

**Comment by Adriandmen** [comment]
Yeah, that is a problem I have a lot. It can be fixed by doing the following:

```
if stack:
   b = pop_stack(1)
   a = pop_stack(1)
else:
   a = pop_stack(1)
   b = pop_stack(1)
```

**Comment by vendethiel** [comment]
Okay, I'll try that. Btw, is there a syntax for arrays in the langauge? `[1,2]` is obviously an infinite loop...

**Comment by Adriandmen** [comment]
There actually isn't. You can do that with for example `1 2)`, which wraps the entire stack into an array, but in this particular case you can also do `12S`.

**Comment by Adriandmen** [comment]
Or even `2L`.

**Comment by vendethiel** [comment]
Okay, new test cases:

```
$ cat test                                                                                                                                                                                                                            :(
10"_".ø=
"hey""-".ø=
2L0.ø=
$ python3 05AB1E.py test
_10_
-hey-
['0', 1, 2, '0']
```

**Comment by vendethiel** [comment]
As well as:

```
$ cat test
.ø
$ python3 05AB1E.py test
10
_
_10_
$ python3 05AB1E.py test
[1,2,3]
0
['0', 1, 2, 3, '0']
```

**Comment by Adriandmen** [comment]
That looks perfect! Thanks :).

**Comment by vendethiel** [comment]
Last but not least, doc-wise... Does this go to Info.txt or List-Commands.txt?

**Comment by Adriandmen** [comment]
This goes at the bottom of Info.txt
