### ISSUE TITLE
Add a padding command

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#41]
pls do it

**Comment by GolfingSuccess** [comment]
You mean, `[1,2,3]4 3<rightpad>` will do something like `[1,2,3,4,4,4]`?

**Comment by michaelsanford** [comment]
Interested in this one, too (feel free to assign it) @Adriandmen .

I have the same question as Έρικ on what the behaviour should be. Perhaps just comment with a test 😄

**Comment by Adriandmen** [comment]
I think this has become redundant as prepending and appending can be done with `a b c×«` or `a b c×ì` for strings, which would take two bytes in total.

I'm not sure if there exists a one-byte command that turns `4 3 <list multiply>`  into `[4, 4, 4]`, but that would make a padding command obsolete.

**Comment by GolfingSuccess** [comment]
@Adriandmen It would be `s¸.×«` for my suggested behavior if I'm correct, better to have a pad command.

**Comment by Adriandmen** [comment]
@GolfingSuccess Yes, but with a `list multiply` one byte command, it would be two bytes in total. Perhaps a rewrite of the `.×` command would be sufficient enough. I'll look into this tomorrow.

**Comment by Adriandmen** [comment]
Made redundant in the latest commit: https://github.com/Adriandmen/05AB1E/commit/f9cd7bfae81d42d24d031a661b9af8f11b8e5f48 by combining the two commands:

 - Prepend: `иì`
 - Append: `и«`
