### ISSUE TITLE
© doesn't request input when called on an empty stack

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#42]

**Comment by GolfingSuccess** [comment]
Make it pop from the stack, push to register, and push to the stack again :)

**Comment by GolfingSuccess** [comment]
+ First, do `D` (05AB1E) and pop the ToS.
+ Then, do `©` as normal.
+ If length of the stack is 1, pop the ToS. Else, leave it there.

**Comment by Adriandmen** [comment]
It's kinda useless since `¹`, `²` and `³` do about the same thing.
