### ISSUE TITLE
Đ

### ISSUE THREAD

**Issue by GolfingSuccess** [Adriandmen/05AB1E#49]
Try `1Đ)`. Instead of `['1', '1', '1']`, it just prints `['1']`. It's like `Đ` doesn't do anything at all.

**Comment by GolfingSuccess** [comment]
It's easy to implement it: `DD` in 05AB1E.

**Comment by Adriandmen** [comment]
You're using `Đ` which is different from `Ð`. There is no problem in the source code.

**Comment by vendethiel** [comment]
ಠ_ಠ
