### ISSUE TITLE
Add popping functions, please.

### ISSUE THREAD

**Issue by GolfingSuccess** [Adriandmen/05AB1E#50]
Please implement a function that pops the ToS, and a function that pops both the ToS and the SToS.

**Comment by Adriandmen** [comment]
Isn't this already implemented?: `\`

**Comment by GolfingSuccess** [comment]
@Adriandmen Well, I think redocumenting `\` as `pop stack` instead of `delete last item` would help though. Sorry for the inconvenience :)
