### ISSUE TITLE
Suggestion: Please use '.' only for extended commands.

### ISSUE THREAD

**Issue by GolfingSuccess** [Adriandmen/05AB1E#51]
This is more of a suggestion than an issue, so please label it as "enhancement".

You are using `<byte>` and `.<byte>` right now. I'd suggest that you do not use `..` as a single command, rather than a marker saying that this is a 3-byte command (that is, if they are needed in the future).

+ `<byte>`: 1-byte commands.
+ `.<byte>`: 2-byte commands.
+ `..<byte>`: 3-byte commands.
+ `...<byte>`: 4-byte commands.
+ etc...

(Yes I didn't purposefully post many issues here, it just happened)

**Comment by GolfingSuccess** [comment]
<h1>I'd suggest implementing it like this.</h1>Let's suppose you have a list of lists like this:

    commands = [_0, _1, _2, ...]
Each list holds its respective commands (let's use `_5` here, as you have encountered 5 dots):

    _5 = [_5_0, _5_1, ...]
Let's say the byte you finally encountered is `7` (not actual `7` byte, just the index). Then, you do this:

    commands[5][7]()
Which is effectively the same as this:

    _5_7()
Note that you should actually name the functions appropriately, I was just giving an example here.<h1>Note: You can implement it differently if you want.

**Comment by Adriandmen** [comment]
I think that this shouldn't be an issue, since a _lot_ of the extended commands are still unimplemented. In fact, there also is `Å` for extended math commands which also has a lot of unimplemented commands.

**Comment by GolfingSuccess** [comment]
@Adriandmen was talking about far, far future here

**Comment by Adriandmen** [comment]
@GolfingSuccess Ahh okay, we'll see if 05AB1E would still be active by then :p
