### ISSUE TITLE
Add a ms sleeping built-in, please. [enhancement]

### ISSUE THREAD

**Issue by GolfingSuccess** [Adriandmen/05AB1E#53]
No, I don't mean `w` (s), I mean a sleeping built-in that waits for 1ms. Consider this example program, where `<built-in>` denotes the builtin I described:

Print dots in an infinite loop, waiting 500ms before printing each `.`.
```
[500F<built-in>}'.?
```
Right now, this is not possible, due to the nonexistence of such a builtin. Can you please add that for me?

**Comment by Adriandmen** [comment]
Added as `.W` in the latest commit: https://github.com/Adriandmen/05AB1E/commit/5e7ffd748e8597bbe45ecf9f34f06efa069f2a3d

**Comment by GolfingSuccess** [comment]
:+1:

**Comment by GolfingSuccess** [comment]
@Adriandmen [`.W` does not work.](//tio.run/nexus/05ab1e#@29qYGCgF/7/PwA) I have verified that DennisMitchell has pulled 05AB1E.

**Comment by Adriandmen** [comment]
Yep, forgot something while implementing it. It's fixed now.

**Comment by GolfingSuccess** [comment]
A last question: Can you add that to Info.txt?
