### ISSUE TITLE
How to use global array?

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#55]
I cannot get global array to work `1ˆ¯)` I expect `1` to be saved in global array and then to be taken from there and printed. Instead in debug mode I'm getting 

```
local variable 'global_array' referenced before assignment
```

and an empty array as the result. Is this intentional?

**Comment by AndrewSav** [comment]
Can be fixed by adding

before this line:
`global global_array`
https://github.com/Adriandmen/05AB1E/blob/master/05AB1E.py#L3728

**Comment by Adriandmen** [comment]
Sorry for the late reply, I had a busy week. This bug has been fixed in the following commit: https://github.com/Adriandmen/05AB1E/commit/a95a5b8a634c8cb3df7d38ae2f8c2ece6ea1cf45
