### ISSUE TITLE
'j' command hangs the program

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#56]
Try running `TTj` it will hang first and then will crash with "MemoryError" exception.
This is possibly because the code adds to the stack, while iterating on in. Perhaps using a temporary array could resolve the issue. I'm actually not sure what this command is supposed to do at all, so sorry that I cannot provide a better suggestion.

**Comment by Adriandmen** [comment]
Yep, which is actually weird since it used to work in October 2016: http://codegolf.stackexchange.com/a/96632/34388

It has been fixed in the latest commit, thanks: https://github.com/Adriandmen/05AB1E/commit/a95a5b8a634c8cb3df7d38ae2f8c2ece6ea1cf45
