### ISSUE TITLE
'k' command description does not match implementation

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#57]
The info file says that k returns 1-based index, whereas the code returns zero based index.

**Comment by Adriandmen** [comment]
The code used to return the one-based index. I later found out that 0-based index is more commonly used, so that was changed. I forgot to change the info.txt but it has been fixed: https://github.com/Adriandmen/05AB1E/commit/a95a5b8a634c8cb3df7d38ae2f8c2ece6ea1cf45
