### ISSUE TITLE
Please double-check implementation of `×`

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#58]
This program: `"bla"T×` results in:
```
blablablablablablablablablabla
```
Which, I'm assuming correct. However this program `"bla"D)T×` does not produce a result, and this program `5D)T×` produces this:
```
['1010101010', '1010101010']
```

It looks, like the latter two cases are not what the intention was. Could you please check?

**Comment by Adriandmen** [comment]
Yes, thanks for spotting! I have also fixed this bug in the latest commit: https://github.com/Adriandmen/05AB1E/commit/a95a5b8a634c8cb3df7d38ae2f8c2ece6ea1cf45
