### ISSUE TITLE
Please double-check implementation of `á`

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#59]
`"1bla2"á` returns `bla`, which is expected. On the other hand `"1bla2"D)á` returns `[[], [], [], [], [], [], [], [], [], []]`, which is not expected at all. I'd expect `['bla','bla']` or something, but then I do not know how it was supposed to work. Could you please double check?

**Comment by AndrewSav** [comment]
Same comment regarding `þ` command.

**Comment by Adriandmen** [comment]
Yep, I should really make unit tests for this haha. It has been fixed: https://github.com/Adriandmen/05AB1E/commit/a95a5b8a634c8cb3df7d38ae2f8c2ece6ea1cf45
