### ISSUE TITLE
Question: what do `.o` and `.O` do?

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#62]
Okay, I give up.
```
.o    = pop a,b    push overlap(b)
.O    = pop a,b    push connected_overlap(b)
```
Could you please explain me what these two do? Thank you in advance!

**Comment by Adriandmen** [comment]
These were actually something I implemented for ASCII art challenges. It works as following:

    "abcdefg""cde".O

The program checks when they overlap each other when prepending spaces:

    abcdefg
      cde

In this case, there need to be two spaces to make them overlap, so it prepends two spaces to the second string. This command however was used _very rarely_ and is no longer supported.
