### ISSUE TITLE
`.J` and `.j` do not print all grid labels

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#63]
This is the program: `"ab""cd""ef""gh""ij")D5.J`
This is the result:
```
    1    2    3
    2   ab   cd   ef   gh   ij
    3   ab   cd   ef   gh   ij
```

As you can see there is 4 and 5 labels missing on the horizontal axis of the grid

**Comment by Adriandmen** [comment]
Ah, the memories :). This was one of the first commands built into 05AB1E.

It has been very rarely used and is partially replaced by `»` (on 2D arrays) and is therefore deprecated.
