### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by kiwih** [Adriandmen/05AB1E#64]
You haven't chosen to add a license to your work. 
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Please see https://help.github.com/articles/licensing-a-repository/
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

I'd like to use your part of your work in a project of my own - but I can't without your code being under a permissive license.

Thanks!

**Comment by Adriandmen** [comment]
Thank you, it's now added: https://github.com/Adriandmen/05AB1E/blob/master/LICENSE.txt
