### ISSUE TITLE
Add getting nth root

### ISSUE THREAD

**Issue by okx-code** [Adriandmen/05AB1E#65]
I'd  like to be able to get the nth root of a number, possibly there would be a function to get the square and cube root and also the nth root, where it would calculate a√b or b√a, whichever seems most appropriate.

**Comment by Adriandmen** [comment]
Well, right now `zm` does that. For example, for 3√27, you would need something like `27 3zm`. For the square root, you can also use the `t` command. Does this answer your question?

**Comment by okx-code** [comment]
Yeah, thanks.
