### ISSUE TITLE
`E` command only pushes input, does not eval

### ISSUE THREAD

**Issue by nickbclifford** [Adriandmen/05AB1E#67]
In the documentation, the `E` command is said to pop nothing and push `eval(input())`. However, it just pushes input to the stack. This is because all the code does is push to stack without adding to input history.

```python
elif current_command == "E":
    a = get_input()
    stack.append(a)
```

I'm assuming that this is unintended behavior, because the documentation says otherwise.

**Comment by Adriandmen** [comment]
Actually, this command uses the `get_input` method, which does evaluate the input:

```python
def get_input():
    a = input()
    if is_array(a):
        a = ast.literal_eval(a)

    recent_inputs.append(a)
    return a
```
