### ISSUE TITLE
Arbitrary base conversion

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#71]
ayy

**Comment by GolfingSuccess** [comment]
I'd suggest negative base conversion too (like negabinary).

**Comment by Adriandmen** [comment]
Added in the following commit: https://github.com/Adriandmen/05AB1E/commit/9d555af868cb956cc07d68b6066a75673c7b60dd

**Comment by GolfingSuccess** [comment]
Does it support negative base conversion?

**Comment by Adriandmen** [comment]
[Yes it does](https://tio.run/nexus/05ab1e#@29ubq5gpHFh0///AA)
