### ISSUE TITLE
Convert prime(n) --> n

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#72]
hmm

**Comment by gozur** [comment]
CAN WE GET THIS ALREADY PLEASE @Adriandmen

**Comment by vendethiel** [comment]
I'm not sure I understand what the issue means.

**Comment by Adriandmen** [comment]
@vendethiel Just a simple builtin that converts the **n**th prime to **n**. For example, **13** should give **6**.

**Comment by vendethiel** [comment]
You don't use sympy, right? It seems it'd [be easy using it](http://docs.sympy.org/latest/modules/ntheory.html#sympy.ntheory.generate.Sieve.search).

**Comment by Adriandmen** [comment]
Nope, no sympy. But even without should be easy to implement.

**Comment by GolfingSuccess** [comment]
@Adriandmen is it really easy? if so why don't we have it yet? laziness? :p

**Comment by michaelsanford** [comment]
So, the inverse of [what `Ø` does](https://github.com/Adriandmen/05AB1E/blob/master/docs/info.txt)?

Noting that `Ø` is zero-indexed, the input producing `5` would be `13`.

I wrote an implementation. @Adriandmen, which command character do you want it implemented as? I'll send a PR with some tests later this evening.

**Comment by Adriandmen** [comment]
@michaelsanford Neat, thanks! `.Ø` would probably be the best option here and isn't used yet.

**Comment by GolfingSuccess** [comment]
@Adriandmen That's what I thought of too!

**Comment by michaelsanford** [comment]
Small hiccough on a unit test for combinations with `)` but would really like to figure it out myself. I'm sure golfers will understand 😅

**Comment by GolfingSuccess** [comment]
@michaelsanford That seems to be expected behavior (1-deep vectorization).

**Comment by Adriandmen** [comment]
Possibly also a test like:

    2 3) 5 7).Ø          EXPECT `[[0, 1], 2, 3]`

Which could be achieved by using the `single_vectorized_evaluation` method.

**Comment by GolfingSuccess** [comment]
@Adriandmen Is that usually the case for 05AB1E operators? I thought they just vectorize 1-deep.

**Comment by michaelsanford** [comment]
@GolfingSuccess I added the same test to `Ø` and it passes, so I assume so.
