### ISSUE TITLE
String subtraction is deprecated

### ISSUE THREAD

**Issue by Adriandmen** [Adriandmen/05AB1E#77]
fix

**Comment by jeremyruppel** [comment]
Does this refer to the non-decimal usage for the `-` operator? Is there another way do remove all chars in b from a?

**Comment by Adriandmen** [comment]
Right now, the shortest way is to use `SK`, which will also work for decimal strings.

**Comment by Adriandmen** [comment]
[This](https://tio.run/##MzBNTDJM/f9fKTEpOSVVSUEpJVlJIdj7/38A) is an example of how it is used.

**Comment by jeremyruppel** [comment]
😄  that's exactly what I came up with. Thanks for the brilliant golfing language!

**Comment by Adriandmen** [comment]
Fixed at https://github.com/Adriandmen/05AB1E/commit/1e55baac56821f585ec331f93868675e6c7c8b7c
