### ISSUE TITLE
Commits have no valid email address

### ISSUE THREAD

**Issue by schas002** [Adriandmen/05AB1E#8]
Please use your *GitHub* email so we can know that it's you.

**Comment by Adriandmen** [comment]
Lol, I suck at git so I'll need to figure this out. Will work on it.

**Comment by schas002** [comment]
So, there is a thing that happens and two things you have to do:

- You blame a special user, @invalid-email-address, aka `Check your Git settings!`, instead of yourself, for your commits. For example, 0d9b4fbb.

* * *

1\. You have to change your git config so you use your *GitHub* email (found in account settings) for `user.email`. Also, I recommend you to change your `user.name` to your formal name. Example:

```sh
$ git config --global user.name "James Smith"
$ git config --global user.email "jasmith@dispostable.com"
```

2\. You have to blame yourself instead of @invalid-email-address for your commits. Use jayphelps/git-blame-someone-else for this.

```sh
$ git blame-someone-else "James Smith <jasmith@dispostable.com>" ${commit_hash_here}
James Smith <jasmith@dispostable.com> is now the author of c017717. You're officially an a*****e.
```

**Comment by Adriandmen** [comment]
I think this works now, thanks!

**Comment by schas002** [comment]
But the [evil hyphen user](http://github.com/invalid-email-address) is still in the commit history! Why aren't you [blaming yourself](http://github.com/jayphelps/git-blame-someone-else) for your commits that were recorded as invalid email address?
