### ISSUE TITLE
ø is bugged

### ISSUE THREAD

**Issue by GolfingSuccess** [Adriandmen/05AB1E#81]
[Here](https://tio.run/##MzBNTDJM/f/f6PCWwzv@/1dQVFJWUVVT19DU0tbR1dM3MDQyNjE1M7ewtLK2sbWzd3B0cnZxdXP38PTy9vH18w8IDAoOCQ0Lj4iMio6JjYtPSExKTklNS8/IzMrOyc3LLygsKi4pLSuvqKyqrqmtAwA) you can see that `ø` is bugged.

**Comment by Adriandmen** [comment]
That's because the length of the string is uneven, which makes the zip trim the second character of each element. `ζ` is now used for zip with fillers: https://github.com/Adriandmen/05AB1E/commit/df8684ab85db4f6698d18b155de748e10b3d44cb

**Comment by GolfingSuccess** [comment]
Yay I can finally use zipping without `.B`!
