### ISSUE TITLE
Bug: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by scottinet** [Adriandmen/05AB1E#97]
Some commands work on strings or lists but not on integers.

For instance: in [this answer](https://codegolf.stackexchange.com/a/143915/73296) I have to first convert an integer either into a list with `S` or into a string with `§`, otherwise 05AB1E throws the following error: `'int' object is not subscriptable` 

Similarily, some other commands throws an error along the line `'int' object has no length`

It would be nice to convert integers into either a list or a string (depending on the command to apply) instead of throwing an error, when applicable.

I'll fix that issue as soon as I have enough time to test each command against integers and to apply the right conversion beforehand

**Comment by Adriandmen** [comment]
Yeah, these bugs seem to slip from time to time. You are also correct that the variable should be converted to the right type before the command, which is mostly done with the `ast_int_eval` method. An example for the addition command: https://github.com/Adriandmen/05AB1E/blob/master/osabie.py#L652.

Perhaps I should write more unit tests such that it tests all possible types (ints, strings and nested multi-depth lists with ints and strings and possibly more lists).

**Comment by scottinet** [comment]
I'm working on it: I'm doing a huge pass on all commands to fix 2 problems:

* default value when no input and no stack is available: my first fix on the matter was too broad and gives unexpected results. Some commands are doing fine with an empty string, others not so well (for instance, the zero input code outputting a snake is broken because of that). So instead of using empty strings as a global default value, I'm assigning a specific default value to each command (or, sometimes, I let an exception be thrown as it leads to better results)
* type casting when it's needed

I plan on writing an exhaustive PR description with every and all changes made, and I also plan on adding a test case for each change (default value AND type casting) to make sure I don't break anything.

I should be d
